export const ESTIMATOR_TEMPLATES = [
  {
    id: 't-demo-drywall',
    category: 'Demolition',
    name: 'Demolition of drywall & plaster (walls/ceiling)',
    unit: 'sq ft',
    materialCost: 0.10,
    laborHours: 0.05,
  },
  {
    id: 't-demo-flooring',
    category: 'Demolition',
    name: 'Remove existing carpet/tile/hardwood flooring',
    unit: 'sq ft',
    materialCost: 0.05,
    laborHours: 0.08,
  },
  {
    id: 't-demo-fixtures',
    category: 'Demolition',
    name: 'Remove vanity, toilet, tub, or kitchen cabinets',
    unit: 'each',
    materialCost: 5.00,
    laborHours: 2.00,
  },
  {
    id: 't-framing-wood',
    category: 'Framing',
    name: 'Wood stud framing (2x4 or 2x6 partitions)',
    unit: 'linear ft',
    materialCost: 8.50,
    laborHours: 0.25,
  },
  {
    id: 't-drywall-hang',
    category: 'Drywall',
    name: 'Hang & tape 1/2" drywall (moisture resistant in wet areas)',
    unit: 'sq ft',
    materialCost: 0.85,
    laborHours: 0.08,
  },
  {
    id: 't-drywall-finish',
    category: 'Drywall',
    name: 'Mud, sand, & finish drywall (Level 4 texture)',
    unit: 'sq ft',
    materialCost: 0.30,
    laborHours: 0.10,
  },
  {
    id: 't-plumb-rough',
    category: 'Plumbing',
    name: 'Rough-in plumbing (supply & waste lines per fixture)',
    unit: 'each',
    materialCost: 150.00,
    laborHours: 6.00,
  },
  {
    id: 't-plumb-fixture',
    category: 'Plumbing',
    name: 'Install plumbing fixture (toilet, sink, or faucet)',
    unit: 'each',
    materialCost: 120.00,
    laborHours: 2.50,
  },
  {
    id: 't-plumb-shower',
    category: 'Plumbing',
    name: 'Install custom shower pan & valve rough-in',
    unit: 'each',
    materialCost: 350.00,
    laborHours: 8.00,
  },
  {
    id: 't-elec-rough',
    category: 'Electrical',
    name: 'Rough-in electrical circuit (wire + box + switch/outlet)',
    unit: 'each',
    materialCost: 450.00,
    laborHours: 5.00,
  },
  {
    id: 't-elec-light',
    category: 'Electrical',
    name: 'Install recessed LED light fixture',
    unit: 'each',
    materialCost: 35.00,
    laborHours: 1.00,
  },
  {
    id: 't-tile-floor',
    category: 'Tile & Stone',
    name: 'Install floor tile (porcelain/ceramic) + thinset & grout',
    unit: 'sq ft',
    materialCost: 4.50,
    laborHours: 0.75,
  },
  {
    id: 't-tile-shower',
    category: 'Tile & Stone',
    name: 'Install custom tiled shower walls (waterproof substrate)',
    unit: 'sq ft',
    materialCost: 7.00,
    laborHours: 1.20,
  },
  {
    id: 't-paint-walls',
    category: 'Painting',
    name: 'Prime & paint walls (2 coats latex paint)',
    unit: 'sq ft',
    materialCost: 0.45,
    laborHours: 0.04,
  },
  {
    id: 't-paint-trim',
    category: 'Painting',
    name: 'Prep & paint trim/doors (semi-gloss)',
    unit: 'linear ft',
    materialCost: 0.35,
    laborHours: 0.06,
  },
  {
    id: 't-trim-door',
    category: 'Trim & Finish',
    name: 'Install pre-hung interior door & casing',
    unit: 'each',
    materialCost: 180.00,
    laborHours: 2.00,
  },
  {
    id: 't-trim-baseboard',
    category: 'Trim & Finish',
    name: 'Install baseboard moulding (MDF/wood)',
    unit: 'linear ft',
    materialCost: 2.20,
    laborHours: 0.08,
  },
  {
    id: 't-cabinet-install',
    category: 'Cabinets & Tops',
    name: 'Install stock kitchen/bath cabinet boxes',
    unit: 'each',
    materialCost: 250.00,
    laborHours: 1.50,
  },
];

export const CATEGORIES = [
  'Demolition',
  'Framing',
  'Drywall',
  'Plumbing',
  'Electrical',
  'Tile & Stone',
  'Painting',
  'Trim & Finish',
  'Cabinets & Tops',
  'HVAC & Venting',
  'Insulation',
  'Permits & Fees',
  'Other',
];
